---
classes:
  - wso2am
pack_filename: "%{::product_name}-%{::product_version}.zip"
pack_extracted_dir: "%{::product_name}-%{::product_version}"
template_list :
  - repository/conf/carbon.xml
  - bin/wso2server.sh
service_name: wso2am
service_template: wso2base/wso2service.erb
file_list: []
