---
classes:
  - wso2am
pack_extracted_dir:
pack_filename:
template_list :
  - repository/conf/carbon.xml
  - bin/wso2server.sh
service_name: wso2am
file_list: []
pack_filename: "%{::product_name}-%{::product_version}.zip"
pack_extracted_dir: "%{::product_name}-%{::product_version}"
